### ISSUE TITLE
TikTok-Phishing-V3

### ISSUE THREAD

**Issue by M4nifest0** [swagkarna/TikTok-Phishing-V3#1]
.

**Comment by M4nifest0** [comment]
Respectfully deleted altogether

**Comment by swagkarna** [comment]
See M4nifest0 i have not warned you . You can use my tool and you can modify according to your need. But my intention is not to sale any tool in github as it is opensource..Thats it

**Comment by M4nifest0** [comment]
You are right
But I made some changes
Thank you for your reaction
Anyway, you were unhappy because you were your main source
I made things a little easier with a few changes
Anyway, I apologize to you for this
Good luck

**Comment by graysuit** [comment]
@swagkarna  
You can specify the rights of your code in LICENSE file which is specially designed for it. Like
>You can modify, use but you can't use code for commercial purposes unless you have written permission of author.

It will prevent upcoming sellers.

**Comment by swagkarna** [comment]
> @swagkarna
> You can specify the rights of your code in LICENSE file which is specially designed for it. Like
> 
> > You can modify, use but you can't use code for commercial purposes unless you have written permission of author.
> 
> It will prevent upcoming sellers.

Thanks for your suggestion.....
