### ISSUE TITLE
Wah Wah maza aagya !

### ISSUE THREAD

**Issue by graysuit** [swagkarna/TikTok-Phishing-V3#2]
I watched the full video and liked the UI and working of tiktok phishing.
But I will be more happy if it would in the code format Not in zip.
Because I mostly view code at github online.
And I can modify it to minimalist form.

**Comment by swagkarna** [comment]
Thanks for your suggestion...But Uploading Zip file to hosting site is quite easy..So i have uploaded zip file.Thats it....
